export interface UserProfile {
  flags: number;
  self: boolean;
  contact: boolean;
  mutualContact: boolean;
  deleted: boolean;
  bot: boolean;
  botChatHistory: boolean;
  botNochats: boolean;
  verified: boolean;
  restricted: boolean;
  min: boolean;
  botInlineGeo: boolean;
  support: boolean;
  scam: boolean;
  applyMinPhoto: boolean;
  fake: boolean;
  botAttachMenu: boolean;
  premium: boolean;
  attachMenuEnabled: boolean;
  flags2: number;
  botCanEdit: boolean;
  closeFriend: boolean;
  storiesHidden: boolean;
  storiesUnavailable: boolean;
  contactRequirePremium: boolean;
  botBusiness: boolean;
  botHasMainApp: boolean;
  id: string;
  accessHash: string;
  firstName: string;
  lastName: string;
  username: string;
  phone: string;
  photo: string | null;
  status: {
    wasOnline: number;
    className: string;
  } | null;
  botInfoVersion: number | null;
  restrictionReason: string | null;
  botInlinePlaceholder: string | null;
  langCode: string | null;
  emojiStatus: string | null;
  usernames: string | null;
  storiesMaxId: string | null;
  color: string | null;
  profileColor: string | null;
  botActiveUsers: number | null;
  botVerificationIcon: string | null;
  className: string;
}
