export interface TelegramChatFull {
  fullChat: {
    flags: number;
    canViewParticipants: boolean;
    canSetUsername: boolean;
    canSetStickers: boolean;
    hiddenPrehistory: boolean;
    canSetLocation: boolean;
    hasScheduled: boolean;
    canViewStats: boolean;
    blocked: boolean;
    flags2: number;
    canDeleteChannel: boolean;
    antispam: boolean;
    participantsHidden: boolean;
    translationsDisabled: boolean;
    storiesPinnedAvailable: boolean;
    viewForumAsMessages: boolean;
    restrictedSponsored: boolean;
    canViewRevenue: boolean;
    paidMediaAllowed: boolean;
    canViewStarsRevenue: boolean;
    paidReactionsAvailable: boolean;
    stargiftsAvailable: boolean;
    id: string;
    about: string;
    participantsCount: number;
    adminsCount: number;
    kickedCount: number;
    bannedCount: number;
    onlineCount: number | null;
    readInboxMaxId: number;
    readOutboxMaxId: number;
    unreadCount: number;
    chatPhoto: {
      id: string;
      className: string;
    };
    notifySettings: {
      flags: number;
      showPreviews: boolean | null;
      silent: boolean | null;
      muteUntil: number | null;
      iosSound: string | null;
      androidSound: string | null;
      otherSound: string | null;
      storiesMuted: boolean | null;
      storiesHideSender: boolean | null;
      storiesIosSound: string | null;
      storiesAndroidSound: string | null;
      storiesOtherSound: string | null;
      className: string;
    };
    exportedInvite: {
      flags: number;
      revoked: boolean;
      permanent: boolean;
      requestNeeded: boolean;
      link: string;
      adminId: string;
      date: number;
      startDate: number | null;
      expireDate: number | null;
      usageLimit: number | null;
      usage: number | null;
      requested: number | null;
      subscriptionExpired: number | null;
      title: string | null;
      subscriptionPricing: string | null;
      className: string;
    };
    botInfo: {
      flags: number;
      hasPreviewMedias: boolean;
      userId: string;
      description: string | null;
      descriptionPhoto: string | null;
      descriptionDocument: string | null;
      commands: string | null;
      menuButton: string | null;
      privacyPolicyUrl: string | null;
      appSettings: string | null;
      verifierSettings: string | null;
      className: string;
    }[];
    migratedFromChatId: string | null;
    migratedFromMaxId: string | null;
    pinnedMsgId: string | null;
    stickerset: string | null;
    availableMinId: string | null;
    folderId: string | null;
    linkedChatId: string | null;
    location: string | null;
    slowmodeSeconds: number | null;
    slowmodeNextSendDate: number | null;
    statsDc: number;
    pts: number;
    call: string | null;
    ttlPeriod: number | null;
    pendingSuggestions: string | null;
    groupcallDefaultJoinAs: string | null;
    themeEmoticon: string | null;
    requestsPending: number | null;
    recentRequesters: string | null;
    defaultSendAs: string | null;
    availableReactions: {
      flags: number;
      allowCustom: boolean;
      className: string;
    };
    reactionsLimit: number | null;
    stories: string | null;
    wallpaper: string | null;
    boostsApplied: string | null;
    boostsUnrestrict: string | null;
    emojiset: string | null;
    botVerification: string | null;
    stargiftsCount: number | null;
    className: string;
  };
  chats: {
    flags: number;
    creator: boolean;
    left: boolean;
    broadcast: boolean;
    verified: boolean;
    megagroup: boolean;
    restricted: boolean;
    signatures: boolean;
    min: boolean;
    scam: boolean;
    hasLink: boolean;
    hasGeo: boolean;
    slowmodeEnabled: boolean;
    callActive: boolean;
    callNotEmpty: boolean;
    fake: boolean;
    gigagroup: boolean;
    noforwards: boolean;
    joinToSend: boolean;
    joinRequest: boolean;
    forum: boolean;
    flags2: number;
    storiesHidden: boolean;
    storiesHiddenMin: boolean;
    storiesUnavailable: boolean;
    signatureProfiles: boolean;
    id: string;
    accessHash: string;
    title: string;
    username: string | null;
    photo: {
      className: string;
    };
    date: number;
    restrictionReason: string | null;
    adminRights: {
      flags: number;
      changeInfo: boolean;
      postMessages: boolean;
      editMessages: boolean;
      deleteMessages: boolean;
      banUsers: boolean;
      inviteUsers: boolean;
      pinMessages: boolean;
      addAdmins: boolean;
      anonymous: boolean;
      manageCall: boolean;
      other: boolean;
      manageTopics: boolean;
      postStories: boolean;
      editStories: boolean;
      deleteStories: boolean;
      className: string;
    } | null;
    bannedRights: string | null;
    defaultBannedRights: string | null;
    participantsCount: number | null;
    usernames: string | null;
    storiesMaxId: string | null;
    color: string | null;
    profileColor: string | null;
    emojiStatus: string | null;
    level: string | null;
    subscriptionUntilDate: number | null;
    botVerificationIcon: string | null;
    className: string;
  }[];
  users: {
    flags: number;
    self: boolean;
    contact: boolean;
    mutualContact: boolean;
    deleted: boolean;
    bot: boolean;
    botChatHistory: boolean;
    botNochats: boolean;
    verified: boolean;
    restricted: boolean;
    min: boolean;
    botInlineGeo: boolean;
    support: boolean;
    scam: boolean;
    applyMinPhoto: boolean;
    fake: boolean;
    botAttachMenu: boolean;
    premium: boolean;
    attachMenuEnabled: boolean;
    flags2: number;
    botCanEdit: boolean;
    closeFriend: boolean;
    storiesHidden: boolean;
    storiesUnavailable: boolean;
    contactRequirePremium: boolean;
    botBusiness: boolean;
    botHasMainApp: boolean;
    id: string;
    accessHash: string;
    firstName: string;
    lastName: string | null;
    username: string | null;
    phone: string | null;
    photo: string | null;
    status: {
      wasOnline: number;
      className: string;
    } | null;
    botInfoVersion: number | null;
    restrictionReason: string | null;
    botInlinePlaceholder: string | null;
    langCode: string | null;
    emojiStatus: string | null;
    usernames: string | null;
    storiesMaxId: string | null;
    color: string | null;
    profileColor: string | null;
    botActiveUsers: string | null;
    botVerificationIcon: string | null;
    className: string;
  }[];
  className: string;
}
